#
# Module manifest for the OS Configuration Management module.
#
# Generated by: Microsoft Corporation
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Microsoft.Management.OsConfiguration.Commands.dll'

# Version number of this module.
ModuleVersion = '1.1.3.0'

# ID used to uniquely identify this module
GUID = '1C9FF8EE-E567-4883-A532-4087D40BC5D6'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'DmOsConfigurationDocumentInfo.ps1xml',
    'OsConfigurationInfo.ps1xml'
    )

# Cmdlets to export from this module
CmdletsToExport = @(
    'Get-OsConfigurationDocument',
    'Get-OsConfigurationDocumentContent',
    'Get-OsConfigurationDocumentResult',
    'Get-OsConfigurationProperty'
    'Remove-OsConfigurationDocument',
    'Set-OsConfigurationDocument',
    'Set-OsConfigurationProperty',
    'Get-OSConfiguration'
    )

# HelpInfo - TBD
HelpInfoUri = "https://aka.ms/winsvr-2025-pshelp"

CompatiblePSEditions = @('Desktop', 'Core')
}

